# Generated by Django 4.2 on 2024-11-26 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='phone_name',
            field=models.CharField(max_length=50),
        ),
    ]
