# Generated by Django 4.2 on 2024-11-27 06:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('brands', '0002_alter_brand_brand_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='brand',
            old_name='brand_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='brand',
            old_name='brand_nationality',
            new_name='nationality',
        ),
    ]
